<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="../css/bootstrap.min.css" rel="stylesheet">
    <link href="../css/bootstrap-theme.css" rel="stylesheet">
    <script src="../js//jquery-3.1.1.min.js"></script>
    <script src="../js/bootstrap.min.js"></script> 
    <!--<link href="../css/style.css" rel="stylesheet">-->
    
</head>
<body><font face="Comic Sans MS,verdana">
    <div class="container">
        <div class="row">
            <h3 style="text-align:center">INGRESO DE PERSONAL</h3>
        </div>
        <form class="form-horizontal" method="POST"  action="../operaciones/modulos/insertar_persona.php" enctype="multipart/form-data">
            <div class="form-group">
                <label  class="col-sm-2 control-label">Cedula</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="cedula" name="cedula" placeholder="Cedula" required>
                </div>
            </div>
            <div class="form-group">
                <label for="nombre" class="col-sm-2 control-label">Nombre 1</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="nombre_1" name="nombre_1" placeholder="Nombre 1" required>
                </div>
            </div>
            <div class="form-group">
                <label for="nombre" class="col-sm-2 control-label">Nombre 2</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="nombre_2" name="nombre 2" placeholder="Nombre 2" required>
                </div>
            </div>
            <div class="form-group">
                <label for="nombre" class="col-sm-2 control-label">Apellido 1</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="apellido_1" name="apellido 1" placeholder="Apellido 1" required>
                </div>
            </div>
            <div class="form-group">
                <label for="nombre" class="col-sm-2 control-label">Apellido 2</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="apellido_2" name="apellido 2" placeholder="Apellido 2" required>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Fecha Nacimiento</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="nac" name="nac" placeholder="Fecha Nacimiento" required>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Ciudad Nacimiento</label>
                <div class="col-sm-10">
                    <select class="form-control" id="c_na" name="c_na">
                        <option value="0"></option>
                         <option value="5001">MEDELLÍN</option>
                         <option value="5002">ABEJORRAL</option>
                         <option value="5004">ABRIAQUÍ</option>
                         <option value="5021">ALEJANDRÍA</option>
                         <option value="5030">AMAGÁ</option>
                         <option value="5031">AMALFI</option>
                         <option value="5034">ANDES</option>
                         <option value="5036">ANGELÓPOLIS</option>
                         <option value="5038">ANGOSTURA</option>
                         <option value="5040">ANORÍ</option>
                         <option value="5042">SANTAFÉ DE ANTIOQUIA</option>
                         <option value="5044">ANZA</option>
                         <option value="5045">APARTADÓ</option>
                         <option value="5051">ARBOLETES</option>
                         <option value="5055">ARGELIA</option>
                         <option value="5059">ARMENIA</option>
                         <option value="5079">BARBOSA</option>
                         <option value="5086">BELMIRA</option>
                         <option value="5088">BELLO</option>
                         <option value="5091">BETANIA</option>
                         <option value="5093">BETULIA</option>
                         <option value="5101">CIUDAD BOLÍVAR</option>
                         <option value="5107">BRICEÑO</option>
                         <option value="5113">BURITICÁ</option>
                         <option value="5120">CÁCERES</option>
                         <option value="5125">CAICEDO</option>
                         <option value="5129">CALDAS</option>
                         <option value="5134">CAMPAMENTO</option>
                         <option value="5138">CAÑASGORDAS</option>
                         <option value="5142">CARACOLÍ</option>
                         <option value="5145">CARAMANTA</option>
                         <option value="5147">CAREPA</option>
                         <option value="5148">EL CARMEN DE VIBORAL</option>
                         <option value="5150">CAROLINA</option>
                         <option value="5154">CAUCASIA</option>
                         <option value="5172">CHIGORODÓ</option>
                         <option value="5190">CISNEROS</option>
                         <option value="5197">COCORNÁ</option>
                         <option value="5206">CONCEPCIÓN</option>
                         <option value="5209">CONCORDIA</option>
                         <option value="5212">COPACABANA</option>
                         <option value="5234">DABEIBA</option>
                         <option value="5237">DONMATÍAS</option>
                         <option value="5240">EBÉJICO</option>
                         <option value="5250">EL BAGRE</option>
                         <option value="5264">ENTRERRIOS</option>
                         <option value="5266">ENVIGADO</option>
                         <option value="5282">FREDONIA</option>
                         <option value="5284">FRONTINO</option>
                         <option value="5306">GIRALDO</option>
                         <option value="5308">GIRARDOTA</option>
                         <option value="5310">GÓMEZ PLATA</option>
                         <option value="5313">GRANADA</option>
                         <option value="5315">GUADALUPE</option>
                         <option value="5318">GUARNE</option>
                         <option value="5321">GUATAPE</option>
                         <option value="5347">HELICONIA</option>
                         <option value="5353">HISPANIA</option>
                         <option value="5360">ITAGUI</option>
                         <option value="5361">ITUANGO</option>
                         <option value="5364">JARDÍN</option>
                         <option value="5368">JERICÓ</option>
                         <option value="5376">LA CEJA</option>
                         <option value="5380">LA ESTRELLA</option>
                         <option value="5390">LA PINTADA</option>
                         <option value="5400">LA UNIÓN</option>
                         <option value="5411">LIBORINA</option>
                         <option value="5425">MACEO</option>
                         <option value="5440">MARINILLA</option>
                         <option value="5467">MONTEBELLO</option>
                         <option value="5475">MURINDÓ</option>
                         <option value="5480">MUTATÁ</option>
                         <option value="5483">NARIÑO</option>
                         <option value="5490">NECOCLÍ</option>
                         <option value="5495">NECHÍ</option>
                         <option value="5501">OLAYA</option>
                         <option value="5541">PEÑOL</option>
                         <option value="5543">PEQUE</option>
                         <option value="5576">PUEBLORRICO</option>
                         <option value="5579">PUERTO BERRÍO</option>
                         <option value="5585">PUERTO NARE</option>
                         <option value="5591">PUERTO TRIUNFO</option>
                         <option value="5604">REMEDIOS</option>
                         <option value="5607">RETIRO</option>
                         <option value="5615">RIONEGRO</option>
                         <option value="5628">SABANALARGA</option>
                         <option value="5631">SABANETA</option>
                         <option value="5642">SALGAR</option>
                         <option value="5647">SAN ANDRÉS DE CUERQUÍA</option>
                         <option value="5649">SAN CARLOS</option>
                         <option value="5652">SAN FRANCISCO</option>
                         <option value="5656">SAN JERÓNIMO</option>
                         <option value="5658">SAN JOSÉ DE LA MONTAÑA</option>
                         <option value="5659">SAN JUAN DE URABÁ</option>
                         <option value="5660">SAN LUIS</option>
                         <option value="5664">SAN PEDRO DE LOS MILAGROS</option>
                         <option value="5665">SAN PEDRO DE URABA</option>
                         <option value="5667">SAN RAFAEL</option>
                         <option value="5670">SAN ROQUE</option>
                         <option value="5674">SAN VICENTE</option>
                         <option value="5679">SANTA BÁRBARA</option>
                         <option value="5686">SANTA ROSA DE OSOS</option>
                         <option value="5690">SANTO DOMINGO</option>
                         <option value="5697">EL SANTUARIO</option>
                         <option value="5736">SEGOVIA</option>
                         <option value="5756">SONSON</option>
                         <option value="5761">SOPETRÁN</option>
                         <option value="5789">TÁMESIS</option>
                         <option value="5790">TARAZÁ</option>
                         <option value="5792">TARSO</option>
                         <option value="5809">TITIRIBÍ</option>
                         <option value="5819">TOLEDO</option>
                         <option value="5837">TURBO</option>
                         <option value="5842">URAMITA</option>
                         <option value="5847">URRAO</option>
                         <option value="5854">VALDIVIA</option>
                         <option value="5856">VALPARAÍSO</option>
                         <option value="5858">VEGACHÍ</option>
                         <option value="5861">VENECIA</option>
                         <option value="5873">VIGÍA DEL FUERTE</option>
                         <option value="5885">YALÍ</option>
                         <option value="5887">YARUMAL</option>
                         <option value="5890">YOLOMBÓ</option>
                         <option value="5893">YONDÓ</option>
                         <option value="5895">ZARAGOZA</option>
                         <option value="8001">BARRANQUILLA</option>
                         <option value="8078">BARANOA</option>
                         <option value="8137">CAMPO DE LA CRUZ</option>
                         <option value="8141">CANDELARIA</option>
                         <option value="8296">GALAPA</option>
                         <option value="8372">JUAN DE ACOSTA</option>
                         <option value="8421">LURUACO</option>
                         <option value="8433">MALAMBO</option>
                         <option value="8436">MANATÍ</option>
                         <option value="8520">PALMAR DE VARELA</option>
                         <option value="8549">PIOJÓ</option>
                         <option value="8558">POLONUEVO</option>
                         <option value="8560">PONEDERA</option>
                         <option value="8573">PUERTO COLOMBIA</option>
                         <option value="8606">REPELÓN</option>
                         <option value="8634">SABANAGRANDE</option>
                         <option value="8638">SABANALARGA</option>
                         <option value="8675">SANTA LUCÍA</option>
                         <option value="8685">SANTO TOMÁS</option>
                         <option value="8758">SOLEDAD</option>
                         <option value="8770">SUAN</option>
                         <option value="8832">TUBARÁ</option>
                         <option value="8849">USIACURÍ</option>
                         <option value="11001">BOGOTÁ, D.C.</option>
                         <option value="13001">CARTAGENA</option>
                         <option value="13006">ACHÍ</option>
                         <option value="13030">ALTOS DEL ROSARIO</option>
                         <option value="13042">ARENAL</option>
                         <option value="13052">ARJONA</option>
                         <option value="13062">ARROYOHONDO</option>
                         <option value="13074">BARRANCO DE LOBA</option>
                         <option value="13140">CALAMAR</option>
                         <option value="13160">CANTAGALLO</option>
                         <option value="13188">CICUCO</option>
                         <option value="13212">CÓRDOBA</option>
                         <option value="13222">CLEMENCIA</option>
                         <option value="13244">EL CARMEN DE BOLÍVAR</option>
                         <option value="13248">EL GUAMO</option>
                         <option value="13268">EL PEÑÓN</option>
                         <option value="13300">HATILLO DE LOBA</option>
                         <option value="13430">MAGANGUÉ</option>
                         <option value="13433">MAHATES</option>
                         <option value="13440">MARGARITA</option>
                         <option value="13442">MARÍA LA BAJA</option>
                         <option value="13458">MONTECRISTO</option>
                         <option value="13468">MOMPÓS</option>
                         <option value="13473">MORALES</option>
                         <option value="13490">NOROSÍ</option>
                         <option value="13549">PINILLOS</option>
                         <option value="13580">REGIDOR</option>
                         <option value="13600">RÍO VIEJO</option>
                         <option value="13620">SAN CRISTÓBAL</option>
                         <option value="13647">SAN ESTANISLAO</option>
                         <option value="13650">SAN FERNANDO</option>
                         <option value="13654">SAN JACINTO</option>
                         <option value="13655">SAN JACINTO DEL CAUCA</option>
                         <option value="13657">SAN JUAN NEPOMUCENO</option>
                         <option value="13667">SAN MARTÍN DE LOBA</option>
                         <option value="13670">SAN PABLO</option>
                         <option value="13673">SANTA CATALINA</option>
                         <option value="13683">SANTA ROSA</option>
                         <option value="13688">SANTA ROSA DEL SUR</option>
                         <option value="13744">SIMITÍ</option>
                         <option value="13760">SOPLAVIENTO</option>
                         <option value="13780">TALAIGUA NUEVO</option>
                         <option value="13810">TIQUISIO</option>
                         <option value="13836">TURBACO</option>
                         <option value="13838">TURBANÁ</option>
                         <option value="13873">VILLANUEVA</option>
                         <option value="13894">ZAMBRANO</option>
                         <option value="15001">TUNJA</option>
                         <option value="15022">ALMEIDA</option>
                         <option value="15047">AQUITANIA</option>
                         <option value="15051">ARCABUCO</option>
                         <option value="15087">BELÉN</option>
                         <option value="15090">BERBEO</option>
                         <option value="15092">BETÉITIVA</option>
                         <option value="15097">BOAVITA</option>
                         <option value="15104">BOYACÁ</option>
                         <option value="15106">BRICEÑO</option>
                         <option value="15109">BUENAVISTA</option>
                         <option value="15114">BUSBANZÁ</option>
                         <option value="15131">CALDAS</option>
                         <option value="15135">CAMPOHERMOSO</option>
                         <option value="15162">CERINZA</option>
                         <option value="15172">CHINAVITA</option>
                         <option value="15176">CHIQUINQUIRÁ</option>
                         <option value="15180">CHISCAS</option>
                         <option value="15183">CHITA</option>
                         <option value="15185">CHITARAQUE</option>
                         <option value="15187">CHIVATÁ</option>
                         <option value="15189">CIÉNEGA</option>
                         <option value="15204">CÓMBITA</option>
                         <option value="15212">COPER</option>
                         <option value="15215">CORRALES</option>
                         <option value="15218">COVARACHÍA</option>
                         <option value="15223">CUBARÁ</option>
                         <option value="15224">CUCAITA</option>
                         <option value="15226">CUÍTIVA</option>
                         <option value="15232">CHÍQUIZA</option>
                         <option value="15236">CHIVOR</option>
                         <option value="15238">DUITAMA</option>
                         <option value="15244">EL COCUY</option>
                         <option value="15248">EL ESPINO</option>
                         <option value="15272">FIRAVITOBA</option>
                         <option value="15276">FLORESTA</option>
                         <option value="15293">GACHANTIVÁ</option>
                         <option value="15296">GAMEZA</option>
                         <option value="15299">GARAGOA</option>
                         <option value="15317">GUACAMAYAS</option>
                         <option value="15322">GUATEQUE</option>
                         <option value="15325">GUAYATÁ</option>
                         <option value="15332">GÜICÁN</option>
                         <option value="15362">IZA</option>
                         <option value="15367">JENESANO</option>
                         <option value="15368">JERICÓ</option>
                         <option value="15377">LABRANZAGRANDE</option>
                         <option value="15380">LA CAPILLA</option>
                         <option value="15401">LA VICTORIA</option>
                         <option value="15403">LA UVITA</option>
                         <option value="15407">VILLA DE LEYVA</option>
                         <option value="15425">MACANAL</option>
                         <option value="15442">MARIPÍ</option>
                         <option value="15455">MIRAFLORES</option>
                         <option value="15464">MONGUA</option>
                         <option value="15466">MONGUÍ</option>
                         <option value="15469">MONIQUIRÁ</option>
                         <option value="15476">MOTAVITA</option>
                         <option value="15480">MUZO</option>
                         <option value="15491">NOBSA</option>
                         <option value="15494">NUEVO COLÓN</option>
                         <option value="15500">OICATÁ</option>
                         <option value="15507">OTANCHE</option>
                         <option value="15511">PACHAVITA</option>
                         <option value="15514">PÁEZ</option>
                         <option value="15516">PAIPA</option>
                         <option value="15518">PAJARITO</option>
                         <option value="15522">PANQUEBA</option>
                         <option value="15531">PAUNA</option>
                         <option value="15533">PAYA</option>
                         <option value="15537">PAZ DE RÍO</option>
                         <option value="15542">PESCA</option>
                         <option value="15550">PISBA</option>
                         <option value="15572">PUERTO BOYACÁ</option>
                         <option value="15580">QUÍPAMA</option>
                         <option value="15599">RAMIRIQUÍ</option>
                         <option value="15600">RÁQUIRA</option>
                         <option value="15621">RONDÓN</option>
                         <option value="15632">SABOYÁ</option>
                         <option value="15638">SÁCHICA</option>
                         <option value="15646">SAMACÁ</option>
                         <option value="15660">SAN EDUARDO</option>
                         <option value="15664">SAN JOSÉ DE PARE</option>
                         <option value="15667">SAN LUIS DE GACENO</option>
                         <option value="15673">SAN MATEO</option>
                         <option value="15676">SAN MIGUEL DE SEMA</option>
                         <option value="15681">SAN PABLO DE BORBUR</option>
                         <option value="15686">SANTANA</option>
                         <option value="15690">SANTA MARÍA</option>
                         <option value="15693">SANTA ROSA DE VITERBO</option>
                         <option value="15696">SANTA SOFÍA</option>
                         <option value="15720">SATIVANORTE</option>
                         <option value="15723">SATIVASUR</option>
                         <option value="15740">SIACHOQUE</option>
                         <option value="15753">SOATÁ</option>
                         <option value="15755">SOCOTÁ</option>
                         <option value="15757">SOCHA</option>
                         <option value="15759">SOGAMOSO</option>
                         <option value="15761">SOMONDOCO</option>
                         <option value="15762">SORA</option>
                         <option value="15763">SOTAQUIRÁ</option>
                         <option value="15764">SORACÁ</option>
                         <option value="15774">SUSACÓN</option>
                         <option value="15776">SUTAMARCHÁN</option>
                         <option value="15778">SUTATENZA</option>
                         <option value="15790">TASCO</option>
                         <option value="15798">TENZA</option>
                         <option value="15804">TIBANÁ</option>
                         <option value="15806">TIBASOSA</option>
                         <option value="15808">TINJACÁ</option>
                         <option value="15810">TIPACOQUE</option>
                         <option value="15814">TOCA</option>
                         <option value="15816">TOGÜÍ</option>
                         <option value="15820">TÓPAGA</option>
                         <option value="15822">TOTA</option>
                         <option value="15832">TUNUNGUÁ</option>
                         <option value="15835">TURMEQUÉ</option>
                         <option value="15837">TUTA</option>
                         <option value="15839">TUTAZÁ</option>
                         <option value="15842">UMBITA</option>
                         <option value="15861">VENTAQUEMADA</option>
                         <option value="15879">VIRACACHÁ</option>
                         <option value="15897">ZETAQUIRA</option>
                         <option value="17001">MANIZALES</option>
                         <option value="17013">AGUADAS</option>
                         <option value="17042">ANSERMA</option>
                         <option value="17050">ARANZAZU</option>
                         <option value="17088">BELALCÁZAR</option>
                         <option value="17174">CHINCHINÁ</option>
                         <option value="17272">FILADELFIA</option>
                         <option value="17380">LA DORADA</option>
                         <option value="17388">LA MERCED</option>
                         <option value="17433">MANZANARES</option>
                         <option value="17442">MARMATO</option>
                         <option value="17444">MARQUETALIA</option>
                         <option value="17446">MARULANDA</option>
                         <option value="17486">NEIRA</option>
                         <option value="17495">NORCASIA</option>
                         <option value="17513">PÁCORA</option>
                         <option value="17524">PALESTINA</option>
                         <option value="17541">PENSILVANIA</option>
                         <option value="17614">RIOSUCIO</option>
                         <option value="17616">RISARALDA</option>
                         <option value="17653">SALAMINA</option>
                         <option value="17662">SAMANÁ</option>
                         <option value="17665">SAN JOSÉ</option>
                         <option value="17777">SUPÍA</option>
                         <option value="17867">VICTORIA</option>
                         <option value="17873">VILLAMARÍA</option>
                         <option value="17877">VITERBO</option>
                         <option value="18001">FLORENCIA</option>
                         <option value="18029">ALBANIA</option>
                         <option value="18094">BELÉN DE LOS ANDAQUÍES</option>
                         <option value="18150">CARTAGENA DEL CHAIRÁ</option>
                         <option value="18205">CURILLO</option>
                         <option value="18247">EL DONCELLO</option>
                         <option value="18256">EL PAUJIL</option>
                         <option value="18410">LA MONTAÑITA</option>
                         <option value="18460">MILÁN</option>
                         <option value="18479">MORELIA</option>
                         <option value="18592">PUERTO RICO</option>
                         <option value="18610">SAN JOSÉ DEL FRAGUA</option>
                         <option value="18753">SAN VICENTE DEL CAGUÁN</option>
                         <option value="18756">SOLANO</option>
                         <option value="18785">SOLITA</option>
                         <option value="18860">VALPARAÍSO</option>
                         <option value="19001">POPAYÁN</option>
                         <option value="19022">ALMAGUER</option>
                         <option value="19050">ARGELIA</option>
                         <option value="19075">BALBOA</option>
                         <option value="19100">BOLÍVAR</option>
                         <option value="19110">BUENOS AIRES</option>
                         <option value="19130">CAJIBÍO</option>
                         <option value="19137">CALDONO</option>
                         <option value="19142">CALOTO</option>
                         <option value="19212">CORINTO</option>
                         <option value="19256">EL TAMBO</option>
                         <option value="19290">FLORENCIA</option>
                         <option value="19300">GUACHENÉ</option>
                         <option value="19318">GUAPI</option>
                         <option value="19355">INZÁ</option>
                         <option value="19364">JAMBALÓ</option>
                         <option value="19392">LA SIERRA</option>
                         <option value="19397">LA VEGA</option>
                         <option value="19418">LÓPEZ</option>
                         <option value="19450">MERCADERES</option>
                         <option value="19455">MIRANDA</option>
                         <option value="19473">MORALES</option>
                         <option value="19513">PADILLA</option>
                         <option value="19517">PAEZ</option>
                         <option value="19532">PATÍA</option>
                         <option value="19533">PIAMONTE</option>
                         <option value="19548">PIENDAMÓ</option>
                         <option value="19573">PUERTO TEJADA</option>
                         <option value="19585">PURACÉ</option>
                         <option value="19622">ROSAS</option>
                         <option value="19693">SAN SEBASTIÁN</option>
                         <option value="19698">SANTANDER DE QUILICHAO</option>
                         <option value="19701">SANTA ROSA</option>
                         <option value="19743">SILVIA</option>
                         <option value="19760">SOTARA</option>
                         <option value="19780">SUÁREZ</option>
                         <option value="19785">SUCRE</option>
                         <option value="19807">TIMBÍO</option>
                         <option value="19809">TIMBIQUÍ</option>
                         <option value="19821">TORIBIO</option>
                         <option value="19824">TOTORÓ</option>
                         <option value="19845">VILLA RICA</option>
                         <option value="20001">Valle Del CaucaDUPAR</option>
                         <option value="20011">AGUACHICA</option>
                         <option value="20013">AGUSTÍN CODAZZI</option>
                         <option value="20032">ASTREA</option>
                         <option value="20045">BECERRIL</option>
                         <option value="20060">BOSCONIA</option>
                         <option value="20175">CHIMICHAGUA</option>
                         <option value="20178">CHIRIGUANÁ</option>
                         <option value="20228">CURUMANÍ</option>
                         <option value="20238">EL COPEY</option>
                         <option value="20250">EL PASO</option>
                         <option value="20295">GAMARRA</option>
                         <option value="20310">GONZÁLEZ</option>
                         <option value="20383">LA GLORIA</option>
                         <option value="20400">LA JAGUA DE IBIRICO</option>
                         <option value="20443">MANAURE</option>
                         <option value="20517">PAILITAS</option>
                         <option value="20550">PELAYA</option>
                         <option value="20570">PUEBLO BELLO</option>
                         <option value="20614">RÍO DE ORO</option>
                         <option value="20621">LA PAZ</option>
                         <option value="20710">SAN ALBERTO</option>
                         <option value="20750">SAN DIEGO</option>
                         <option value="20770">SAN MARTÍN</option>
                         <option value="20787">TAMALAMEQUE</option>
                         <option value="23001">MONTERÍA</option>
                         <option value="23068">AYAPEL</option>
                         <option value="23079">BUENAVISTA</option>
                         <option value="23090">CANALETE</option>
                         <option value="23162">CERETÉ</option>
                         <option value="23168">CHIMÁ</option>
                         <option value="23182">CHINÚ</option>
                         <option value="23189">CIÉNAGA DE ORO</option>
                         <option value="23300">COTORRA</option>
                         <option value="23350">LA APARTADA</option>
                         <option value="23417">LORICA</option>
                         <option value="23419">LOS CÓRDOBAS</option>
                         <option value="23464">MOMIL</option>
                         <option value="23466">MONTELÍBANO</option>
                         <option value="23500">MOÑITOS</option>
                         <option value="23555">PLANETA RICA</option>
                         <option value="23570">PUEBLO NUEVO</option>
                         <option value="23574">PUERTO ESCONDIDO</option>
                         <option value="23580">PUERTO LIBERTADOR</option>
                         <option value="23586">PURÍSIMA</option>
                         <option value="23660">SAHAGÚN</option>
                         <option value="23670">SAN ANDRÉS SOTAVENTO</option>
                         <option value="23672">SAN ANTERO</option>
                         <option value="23675">SAN BERNARDO DEL VIENTO</option>
                         <option value="23678">SAN CARLOS</option>
                         <option value="23682">SAN JOSÉ DE URÉ</option>
                         <option value="23686">SAN PELAYO</option>
                         <option value="23807">TIERRALTA</option>
                         <option value="23815">TUCHÍN</option>
                         <option value="23855">VALENCIA</option>
                         <option value="25001">AGUA DE DIOS</option>
                         <option value="25019">ALBÁN</option>
                         <option value="25035">ANAPOIMA</option>
                         <option value="25040">ANOLAIMA</option>
                         <option value="25053">ARBELÁEZ</option>
                         <option value="25086">BELTRÁN</option>
                         <option value="25095">BITUIMA</option>
                         <option value="25099">BOJACÁ</option>
                         <option value="25120">CABRERA</option>
                         <option value="25123">CACHIPAY</option>
                         <option value="25126">CAJICÁ</option>
                         <option value="25148">CAPARRAPÍ</option>
                         <option value="25151">CAQUEZA</option>
                         <option value="25154">CARMEN DE CARUPA</option>
                         <option value="25168">CHAGUANÍ</option>
                         <option value="25175">CHÍA</option>
                         <option value="25178">CHIPAQUE</option>
                         <option value="25181">CHOACHÍ</option>
                         <option value="25183">CHOCONTÁ</option>
                         <option value="25200">COGUA</option>
                         <option value="25214">COTA</option>
                         <option value="25224">CUCUNUBÁ</option>
                         <option value="25245">EL COLEGIO</option>
                         <option value="25258">EL PEÑÓN</option>
                         <option value="25260">EL ROSAL</option>
                         <option value="25269">FACATATIVÁ</option>
                         <option value="25279">FOMEQUE</option>
                         <option value="25281">FOSCA</option>
                         <option value="25286">FUNZA</option>
                         <option value="25288">FÚQUENE</option>
                         <option value="25290">FUSAGASUGÁ</option>
                         <option value="25293">GACHALA</option>
                         <option value="25295">GACHANCIPÁ</option>
                         <option value="25297">GACHETÁ</option>
                         <option value="25299">GAMA</option>
                         <option value="25307">GIRARDOT</option>
                         <option value="25312">GRANADA</option>
                         <option value="25317">GUACHETÁ</option>
                         <option value="25320">GUADUAS</option>
                         <option value="25322">GUASCA</option>
                         <option value="25324">GUATAQUÍ</option>
                         <option value="25326">GUATAVITA</option>
                         <option value="25328">GUAYABAL DE SIQUIMA</option>
                         <option value="25335">GUAYABETAL</option>
                         <option value="25339">GUTIÉRREZ</option>
                         <option value="25368">JERUSALÉN</option>
                         <option value="25372">JUNÍN</option>
                         <option value="25377">LA CALERA</option>
                         <option value="25386">LA MESA</option>
                         <option value="25394">LA PALMA</option>
                         <option value="25398">LA PEÑA</option>
                         <option value="25402">LA VEGA</option>
                         <option value="25407">LENGUAZAQUE</option>
                         <option value="25426">MACHETA</option>
                         <option value="25430">MADRID</option>
                         <option value="25436">MANTA</option>
                         <option value="25438">MEDINA</option>
                         <option value="25473">MOSQUERA</option>
                         <option value="25483">NARIÑO</option>
                         <option value="25486">NEMOCÓN</option>
                         <option value="25488">NILO</option>
                         <option value="25489">NIMAIMA</option>
                         <option value="25491">NOCAIMA</option>
                         <option value="25506">VENECIA</option>
                         <option value="25513">PACHO</option>
                         <option value="25518">PAIME</option>
                         <option value="25524">PANDI</option>
                         <option value="25530">PARATEBUENO</option>
                         <option value="25535">PASCA</option>
                         <option value="25572">PUERTO SALGAR</option>
                         <option value="25580">PULÍ</option>
                         <option value="25592">QUEBRADANEGRA</option>
                         <option value="25594">QUETAME</option>
                         <option value="25596">QUIPILE</option>
                         <option value="25599">APULO</option>
                         <option value="25612">RICAURTE</option>
                         <option value="25645">SAN ANTONIO DEL TEQUENDAMA</option>
                         <option value="25649">SAN BERNARDO</option>
                         <option value="25653">SAN CAYETANO</option>
                         <option value="25658">SAN FRANCISCO</option>
                         <option value="25662">SAN JUAN DE RÍO SECO</option>
                         <option value="25718">SASAIMA</option>
                         <option value="25736">SESQUILÉ</option>
                         <option value="25740">SIBATÉ</option>
                         <option value="25743">SILVANIA</option>
                         <option value="25745">SIMIJACA</option>
                         <option value="25754">SOACHA</option>
                         <option value="25758">SOPÓ</option>
                         <option value="25769">SUBACHOQUE</option>
                         <option value="25772">SUESCA</option>
                         <option value="25777">SUPATÁ</option>
                         <option value="25779">SUSA</option>
                         <option value="25781">SUTATAUSA</option>
                         <option value="25785">TABIO</option>
                         <option value="25793">TAUSA</option>
                         <option value="25797">TENA</option>
                         <option value="25799">TENJO</option>
                         <option value="25805">TIBACUY</option>
                         <option value="25807">TIBIRITA</option>
                         <option value="25815">TOCAIMA</option>
                         <option value="25817">TOCANCIPÁ</option>
                         <option value="25823">TOPAIPÍ</option>
                         <option value="25839">UBALÁ</option>
                         <option value="25841">UBAQUE</option>
                         <option value="25843">VILLA DE SAN DIEGO DE UBATE</option>
                         <option value="25845">UNE</option>
                         <option value="25851">ÚTICA</option>
                         <option value="25862">VERGARA</option>
                         <option value="25867">VIANÍ</option>
                         <option value="25871">VILLAGÓMEZ</option>
                         <option value="25873">VILLAPINZÓN</option>
                         <option value="25875">VILLETA</option>
                         <option value="25878">VIOTÁ</option>
                         <option value="25885">YACOPÍ</option>
                         <option value="25898">ZIPACÓN</option>
                         <option value="25899">ZIPAQUIRÁ</option>
                         <option value="27001">QUIBDÓ</option>
                         <option value="27006">ACANDÍ</option>
                         <option value="27025">ALTO BAUDÓ</option>
                         <option value="27050">ATRATO</option>
                         <option value="27073">BAGADÓ</option>
                         <option value="27075">BAHÍA SOLANO</option>
                         <option value="27077">BAJO BAUDÓ</option>
                         <option value="27099">BOJAYA</option>
                         <option value="27135">EL CANTÓN DEL SAN PABLO</option>
                         <option value="27150">CARMEN DEL DARIÉN</option>
                         <option value="27160">CÉRTEGUI</option>
                         <option value="27205">CONDOTO</option>
                         <option value="27245">EL CARMEN DE ATRATO</option>
                         <option value="27250">EL LITORAL DEL SAN JUAN</option>
                         <option value="27361">ISTMINA</option>
                         <option value="27372">JURADÓ</option>
                         <option value="27413">LLORÓ</option>
                         <option value="27425">MEDIO ATRATO</option>
                         <option value="27430">MEDIO BAUDÓ</option>
                         <option value="27450">MEDIO SAN JUAN</option>
                         <option value="27491">NÓVITA</option>
                         <option value="27495">NUQUÍ</option>
                         <option value="27580">RÍO IRÓ</option>
                         <option value="27600">RÍO QUITO</option>
                         <option value="27615">RIOSUCIO</option>
                         <option value="27660">SAN JOSÉ DEL PALMAR</option>
                         <option value="27745">SIPÍ</option>
                         <option value="27787">TADÓ</option>
                         <option value="27800">UNGUÍA</option>
                         <option value="27810">UNIÓN PANAMERICANA</option>
                         <option value="41001">NEIVA</option>
                         <option value="41006">ACEVEDO</option>
                         <option value="41013">AGRADO</option>
                         <option value="41016">AIPE</option>
                         <option value="41020">ALGECIRAS</option>
                         <option value="41026">ALTAMIRA</option>
                         <option value="41078">BARAYA</option>
                         <option value="41132">CAMPOALEGRE</option>
                         <option value="41206">COLOMBIA</option>
                         <option value="41244">ELÍAS</option>
                         <option value="41298">GARZÓN</option>
                         <option value="41306">GIGANTE</option>
                         <option value="41319">GUADALUPE</option>
                         <option value="41349">HOBO</option>
                         <option value="41357">IQUIRA</option>
                         <option value="41359">ISNOS</option>
                         <option value="41378">LA ARGENTINA</option>
                         <option value="41396">LA PLATA</option>
                         <option value="41483">NÁTAGA</option>
                         <option value="41503">OPORAPA</option>
                         <option value="41518">PAICOL</option>
                         <option value="41524">PALERMO</option>
                         <option value="41530">PALESTINA</option>
                         <option value="41548">PITAL</option>
                         <option value="41551">PITALITO</option>
                         <option value="41615">RIVERA</option>
                         <option value="41660">SALADOBLANCO</option>
                         <option value="41668">SAN AGUSTÍN</option>
                         <option value="41676">SANTA MARÍA</option>
                         <option value="41770">SUAZA</option>
                         <option value="41791">TARQUI</option>
                         <option value="41797">TESALIA</option>
                         <option value="41799">TELLO</option>
                         <option value="41801">TERUEL</option>
                         <option value="41807">TIMANÁ</option>
                         <option value="41872">VILLAVIEJA</option>
                         <option value="41885">YAGUARÁ</option>
                         <option value="44001">RIOHACHA</option>
                         <option value="44035">ALBANIA</option>
                         <option value="44078">BARRANCAS</option>
                         <option value="44090">DIBULLA</option>
                         <option value="44098">DISTRACCIÓN</option>
                         <option value="44110">EL MOLINO</option>
                         <option value="44279">FONSECA</option>
                         <option value="44378">HATONUEVO</option>
                         <option value="44420">LA JAGUA DEL PILAR</option>
                         <option value="44430">MAICAO</option>
                         <option value="44560">MANAURE</option>
                         <option value="44650">SAN JUAN DEL CESAR</option>
                         <option value="44847">URIBIA</option>
                         <option value="44855">URUMITA</option>
                         <option value="44874">VILLANUEVA</option>
                         <option value="47001">SANTA MARTA</option>
                         <option value="47030">ALGARROBO</option>
                         <option value="47053">ARACATACA</option>
                         <option value="47058">ARIGUANÍ</option>
                         <option value="47161">CERRO SAN ANTONIO</option>
                         <option value="47170">CHIVOLO</option>
                         <option value="47189">CIÉNAGA</option>
                         <option value="47205">CONCORDIA</option>
                         <option value="47245">EL BANCO</option>
                         <option value="47258">EL PIÑON</option>
                         <option value="47268">EL RETÉN</option>
                         <option value="47288">FUNDACIÓN</option>
                         <option value="47318">GUAMAL</option>
                         <option value="47460">NUEVA GRANADA</option>
                         <option value="47541">PEDRAZA</option>
                         <option value="47545">PIJIÑO DEL CARMEN</option>
                         <option value="47551">PIVIJAY</option>
                         <option value="47555">PLATO</option>
                         <option value="47570">PUEBLOVIEJO</option>
                         <option value="47605">REMOLINO</option>
                         <option value="47660">SABANAS DE SAN ANGEL</option>
                         <option value="47675">SALAMINA</option>
                         <option value="47692">SAN SEBASTIÁN DE BUENAVISTA</option>
                         <option value="47703">SAN ZENÓN</option>
                         <option value="47707">SANTA ANA</option>
                         <option value="47720">SANTA BÁRBARA DE PINTO</option>
                         <option value="47745">SITIONUEVO</option>
                         <option value="47798">TENERIFE</option>
                         <option value="47960">ZAPAYÁN</option>
                         <option value="47980">ZONA BANANERA</option>
                         <option value="50001">VILLAVICENCIO</option>
                         <option value="50006">ACACÍAS</option>
                         <option value="50110">BARRANCA DE UPÍA</option>
                         <option value="50124">CABUYARO</option>
                         <option value="50150">CASTILLA LA NUEVA</option>
                         <option value="50223">CUBARRAL</option>
                         <option value="50226">CUMARAL</option>
                         <option value="50245">EL CALVARIO</option>
                         <option value="50251">EL CASTILLO</option>
                         <option value="50270">EL DORADO</option>
                         <option value="50287">FUENTE DE ORO</option>
                         <option value="50313">GRANADA</option>
                         <option value="50318">GUAMAL</option>
                         <option value="50325">MAPIRIPÁN</option>
                         <option value="50330">MESETAS</option>
                         <option value="50350">LA MACARENA</option>
                         <option value="50370">URIBE</option>
                         <option value="50400">LEJANÍAS</option>
                         <option value="50450">PUERTO CONCORDIA</option>
                         <option value="50568">PUERTO GAITÁN</option>
                         <option value="50573">PUERTO LÓPEZ</option>
                         <option value="50577">PUERTO LLERAS</option>
                         <option value="50590">PUERTO RICO</option>
                         <option value="50606">RESTREPO</option>
                         <option value="50680">SAN CARLOS DE GUAROA</option>
                         <option value="50683">SAN JUAN DE ARAMA</option>
                         <option value="50686">SAN JUANITO</option>
                         <option value="50689">SAN MARTÍN</option>
                         <option value="50711">VISTAHERMOSA</option>
                         <option value="52001">PASTO</option>
                         <option value="52019">ALBÁN</option>
                         <option value="52022">ALDANA</option>
                         <option value="52036">ANCUYÁ</option>
                         <option value="52051">ARBOLEDA</option>
                         <option value="52079">BARBACOAS</option>
                         <option value="52083">BELÉN</option>
                         <option value="52110">BUESACO</option>
                         <option value="52203">COLÓN</option>
                         <option value="52207">CONSACA</option>
                         <option value="52210">CONTADERO</option>
                         <option value="52215">CÓRDOBA</option>
                         <option value="52224">CUASPUD</option>
                         <option value="52227">CUMBAL</option>
                         <option value="52233">CUMBITARA</option>
                         <option value="52240">CHACHAGÜÍ</option>
                         <option value="52250">EL CHARCO</option>
                         <option value="52254">EL PEÑOL</option>
                         <option value="52256">EL ROSARIO</option>
                         <option value="52258">EL TABLÓN DE GÓMEZ</option>
                         <option value="52260">EL TAMBO</option>
                         <option value="52287">FUNES</option>
                         <option value="52317">GUACHUCAL</option>
                         <option value="52320">GUAITARILLA</option>
                         <option value="52323">GUALMATÁN</option>
                         <option value="52352">ILES</option>
                         <option value="52354">IMUÉS</option>
                         <option value="52356">IPIALES</option>
                         <option value="52378">LA CRUZ</option>
                         <option value="52381">LA FLORIDA</option>
                         <option value="52385">LA LLANADA</option>
                         <option value="52390">LA TOLA</option>
                         <option value="52399">LA UNIÓN</option>
                         <option value="52405">LEIVA</option>
                         <option value="52411">LINARES</option>
                         <option value="52418">LOS ANDES</option>
                         <option value="52427">MAGÜI</option>
                         <option value="52435">MALLAMA</option>
                         <option value="52473">MOSQUERA</option>
                         <option value="52480">NARIÑO</option>
                         <option value="52490">OLAYA HERRERA</option>
                         <option value="52506">OSPINA</option>
                         <option value="52520">FRANCISCO PIZARRO</option>
                         <option value="52540">POLICARPA</option>
                         <option value="52560">POTOSÍ</option>
                         <option value="52565">PROVIDENCIA</option>
                         <option value="52573">PUERRES</option>
                         <option value="52585">PUPIALES</option>
                         <option value="52612">RICAURTE</option>
                         <option value="52621">ROBERTO PAYÁN</option>
                         <option value="52678">SAMANIEGO</option>
                         <option value="52683">SANDONÁ</option>
                         <option value="52685">SAN BERNARDO</option>
                         <option value="52687">SAN LORENZO</option>
                         <option value="52693">SAN PABLO</option>
                         <option value="52694">SAN PEDRO DE CARTAGO</option>
                         <option value="52696">SANTA BÁRBARA</option>
                         <option value="52699">SANTACRUZ</option>
                         <option value="52720">SAPUYES</option>
                         <option value="52786">TAMINANGO</option>
                         <option value="52788">TANGUA</option>
                         <option value="52835">SAN ANDRES DE TUMACO</option>
                         <option value="52838">TÚQUERRES</option>
                         <option value="52885">YACUANQUER</option>
                         <option value="54001">CÚCUTA</option>
                         <option value="54003">ABREGO</option>
                         <option value="54051">ARBOLEDAS</option>
                         <option value="54099">BOCHALEMA</option>
                         <option value="54109">BUCARASICA</option>
                         <option value="54125">CÁCOTA</option>
                         <option value="54128">CACHIRÁ</option>
                         <option value="54172">CHINÁCOTA</option>
                         <option value="54174">CHITAGÁ</option>
                         <option value="54206">CONVENCIÓN</option>
                         <option value="54223">CUCUTILLA</option>
                         <option value="54239">DURANIA</option>
                         <option value="54245">EL CARMEN</option>
                         <option value="54250">EL TARRA</option>
                         <option value="54261">EL ZULIA</option>
                         <option value="54313">GRAMALOTE</option>
                         <option value="54344">HACARÍ</option>
                         <option value="54347">HERRÁN</option>
                         <option value="54377">LABATECA</option>
                         <option value="54385">LA ESPERANZA</option>
                         <option value="54398">LA PLAYA</option>
                         <option value="54405">LOS PATIOS</option>
                         <option value="54418">LOURDES</option>
                         <option value="54480">MUTISCUA</option>
                         <option value="54498">OCAÑA</option>
                         <option value="54518">PAMPLONA</option>
                         <option value="54520">PAMPLONITA</option>
                         <option value="54553">PUERTO SANTANDER</option>
                         <option value="54599">RAGONVALIA</option>
                         <option value="54660">SALAZAR</option>
                         <option value="54670">SAN CALIXTO</option>
                         <option value="54673">SAN CAYETANO</option>
                         <option value="54680">SANTIAGO</option>
                         <option value="54720">SARDINATA</option>
                         <option value="54743">SILOS</option>
                         <option value="54800">TEORAMA</option>
                         <option value="54810">TIBÚ</option>
                         <option value="54820">TOLEDO</option>
                         <option value="54871">VILLA CARO</option>
                         <option value="54874">VILLA DEL ROSARIO</option>
                         <option value="63001">ARMENIA</option>
                         <option value="63111">BUENAVISTA</option>
                         <option value="63130">CALARCA</option>
                         <option value="63190">CIRCASIA</option>
                         <option value="63212">CÓRDOBA</option>
                         <option value="63272">FILANDIA</option>
                         <option value="63302">GÉNOVA</option>
                         <option value="63401">LA TEBAIDA</option>
                         <option value="63470">MONTENEGRO</option>
                         <option value="63548">PIJAO</option>
                         <option value="63594">QUIMBAYA</option>
                         <option value="63690">SALENTO</option>
                         <option value="66001">PEREIRA</option>
                         <option value="66045">APÍA</option>
                         <option value="66075">BALBOA</option>
                         <option value="66088">BELÉN DE UMBRÍA</option>
                         <option value="66170">DOSQUEBRADAS</option>
                         <option value="66318">GUÁTICA</option>
                         <option value="66383">LA CELIA</option>
                         <option value="66400">LA VIRGINIA</option>
                         <option value="66440">MARSELLA</option>
                         <option value="66456">MISTRATÓ</option>
                         <option value="66572">PUEBLO RICO</option>
                         <option value="66594">QUINCHÍA</option>
                         <option value="66682">SANTA ROSA DE CABAL</option>
                         <option value="66687">SANTUARIO</option>
                         <option value="68001">BUCARAMANGA</option>
                         <option value="68013">AGUADA</option>
                         <option value="68020">ALBANIA</option>
                         <option value="68051">ARATOCA</option>
                         <option value="68077">BARBOSA</option>
                         <option value="68079">BARICHARA</option>
                         <option value="68081">BARRANCABERMEJA</option>
                         <option value="68092">BETULIA</option>
                         <option value="68101">BOLÍVAR</option>
                         <option value="68121">CABRERA</option>
                         <option value="68132">CALIFORNIA</option>
                         <option value="68147">CAPITANEJO</option>
                         <option value="68152">CARCASÍ</option>
                         <option value="68160">CEPITÁ</option>
                         <option value="68162">CERRITO</option>
                         <option value="68167">CHARALÁ</option>
                         <option value="68169">CHARTA</option>
                         <option value="68176">CHIMA</option>
                         <option value="68179">CHIPATÁ</option>
                         <option value="68190">CIMITARRA</option>
                         <option value="68207">CONCEPCIÓN</option>
                         <option value="68209">CONFINES</option>
                         <option value="68211">CONTRATACIÓN</option>
                         <option value="68217">COROMORO</option>
                         <option value="68229">CURITÍ</option>
                         <option value="68235">EL CARMEN DE CHUCURÍ</option>
                         <option value="68245">EL GUACAMAYO</option>
                         <option value="68250">EL PEÑÓN</option>
                         <option value="68255">EL PLAYÓN</option>
                         <option value="68264">ENCINO</option>
                         <option value="68266">ENCISO</option>
                         <option value="68271">FLORIÁN</option>
                         <option value="68276">FLORIDABLANCA</option>
                         <option value="68296">GALÁN</option>
                         <option value="68298">GAMBITA</option>
                         <option value="68307">GIRÓN</option>
                         <option value="68318">GUACA</option>
                         <option value="68320">GUADALUPE</option>
                         <option value="68322">GUAPOTÁ</option>
                         <option value="68324">GUAVATÁ</option>
                         <option value="68327">GÜEPSA</option>
                         <option value="68344">HATO</option>
                         <option value="68368">JESÚS MARÍA</option>
                         <option value="68370">JORDÁN</option>
                         <option value="68377">LA BELLEZA</option>
                         <option value="68385">LANDÁZURI</option>
                         <option value="68397">LA PAZ</option>
                         <option value="68406">LEBRIJA</option>
                         <option value="68418">LOS SANTOS</option>
                         <option value="68425">MACARAVITA</option>
                         <option value="68432">MÁLAGA</option>
                         <option value="68444">MATANZA</option>
                         <option value="68464">MOGOTES</option>
                         <option value="68468">MOLAGAVITA</option>
                         <option value="68498">OCAMONTE</option>
                         <option value="68500">OIBA</option>
                         <option value="68502">ONZAGA</option>
                         <option value="68522">PALMAR</option>
                         <option value="68524">PALMAS DEL SOCORRO</option>
                         <option value="68533">PÁRAMO</option>
                         <option value="68547">PIEDECUESTA</option>
                         <option value="68549">PINCHOTE</option>
                         <option value="68572">PUENTE NACIONAL</option>
                         <option value="68573">PUERTO PARRA</option>
                         <option value="68575">PUERTO WILCHES</option>
                         <option value="68615">RIONEGRO</option>
                         <option value="68655">SABANA DE TORRES</option>
                         <option value="68669">SAN ANDRÉS</option>
                         <option value="68673">SAN BENITO</option>
                         <option value="68679">SAN GIL</option>
                         <option value="68682">SAN JOAQUÍN</option>
                         <option value="68684">SAN JOSÉ DE MIRANDA</option>
                         <option value="68686">SAN MIGUEL</option>
                         <option value="68689">SAN VICENTE DE CHUCURÍ</option>
                         <option value="68705">SANTA BÁRBARA</option>
                         <option value="68720">SANTA HELENA DEL OPÓN</option>
                         <option value="68745">SIMACOTA</option>
                         <option value="68755">SOCORRO</option>
                         <option value="68770">SUAITA</option>
                         <option value="68773">SUCRE</option>
                         <option value="68780">SURATÁ</option>
                         <option value="68820">TONA</option>
                         <option value="68855">Valle Del Cauca DE SAN JOSÉ</option>
                         <option value="68861">VÉLEZ</option>
                         <option value="68867">VETAS</option>
                         <option value="68872">VILLANUEVA</option>
                         <option value="68895">ZAPATOCA</option>
                         <option value="70001">SINCELEJO</option>
                         <option value="70110">BUENAVISTA</option>
                         <option value="70124">CAIMITO</option>
                         <option value="70204">COLOSO</option>
                         <option value="70215">COROZAL</option>
                         <option value="70221">COVEÑAS</option>
                         <option value="70230">CHALÁN</option>
                         <option value="70233">EL ROBLE</option>
                         <option value="70235">GALERAS</option>
                         <option value="70265">GUARANDA</option>
                         <option value="70400">LA UNIÓN</option>
                         <option value="70418">LOS PALMITOS</option>
                         <option value="70429">MAJAGUAL</option>
                         <option value="70473">MORROA</option>
                         <option value="70508">OVEJAS</option>
                         <option value="70523">PALMITO</option>
                         <option value="70670">SAMPUÉS</option>
                         <option value="70678">SAN BENITO ABAD</option>
                         <option value="70702">SAN JUAN DE BETULIA</option>
                         <option value="70708">SAN MARCOS</option>
                         <option value="70713">SAN ONOFRE</option>
                         <option value="70717">SAN PEDRO</option>
                         <option value="70742">SAN LUIS DE SINCÉ</option>
                         <option value="70771">SUCRE</option>
                         <option value="70820">SANTIAGO DE TOLÚ</option>
                         <option value="70823">TOLÚ VIEJO</option>
                         <option value="73001">IBAGUÉ</option>
                         <option value="73024">ALPUJARRA</option>
                         <option value="73026">ALVARADO</option>
                         <option value="73030">AMBALEMA</option>
                         <option value="73043">ANZOÁTEGUI</option>
                         <option value="73055">ARMERO</option>
                         <option value="73067">ATACO</option>
                         <option value="73124">CAJAMARCA</option>
                         <option value="73148">CARMEN DE APICALÁ</option>
                         <option value="73152">CASABIANCA</option>
                         <option value="73168">CHAPARRAL</option>
                         <option value="73200">COELLO</option>
                         <option value="73217">COYAIMA</option>
                         <option value="73226">CUNDAY</option>
                         <option value="73236">DOLORES</option>
                         <option value="73268">ESPINAL</option>
                         <option value="73270">FALAN</option>
                         <option value="73275">FLANDES</option>
                         <option value="73283">FRESNO</option>
                         <option value="73319">GUAMO</option>
                         <option value="73347">HERVEO</option>
                         <option value="73349">HONDA</option>
                         <option value="73352">ICONONZO</option>
                         <option value="73408">LÉRIDA</option>
                         <option value="73411">LÍBANO</option>
                         <option value="73443">SAN SEBASTIÁN DE MARIQUITA</option>
                         <option value="73449">MELGAR</option>
                         <option value="73461">MURILLO</option>
                         <option value="73483">NATAGAIMA</option>
                         <option value="73504">ORTEGA</option>
                         <option value="73520">PALOCABILDO</option>
                         <option value="73547">PIEDRAS</option>
                         <option value="73555">PLANADAS</option>
                         <option value="73563">PRADO</option>
                         <option value="73585">PURIFICACIÓN</option>
                         <option value="73616">RIOBLANCO</option>
                         <option value="73622">RONCESValle Del CaucaS</option>
                         <option value="73624">ROVIRA</option>
                         <option value="73671">SALDAÑA</option>
                         <option value="73675">SAN ANTONIO</option>
                         <option value="73678">SAN LUIS</option>
                         <option value="73686">SANTA ISABEL</option>
                         <option value="73770">SUÁREZ</option>
                         <option value="73854">Valle Del Cauca DE SAN JUAN</option>
                         <option value="73861">VENADILLO</option>
                         <option value="73870">VILLAHERMOSA</option>
                         <option value="73873">VILLARRICA</option>
                         <option value="76001">CALI</option>
                         <option value="76020">ALCALÁ</option>
                         <option value="76036">ANDALUCÍA</option>
                         <option value="76041">ANSERMANUEVO</option>
                         <option value="76054">ARGELIA</option>
                         <option value="76100">BOLÍVAR</option>
                         <option value="76109">BUENAVENTURA</option>
                         <option value="76111">GUADALAJARA DE BUGA</option>
                         <option value="76113">BUGALAGRANDE</option>
                         <option value="76122">CAICEDONIA</option>
                         <option value="76126">CALIMA</option>
                         <option value="76130">CANDELARIA</option>
                         <option value="76147">CARTAGO</option>
                         <option value="76233">DAGUA</option>
                         <option value="76243">EL ÁGUILA</option>
                         <option value="76246">EL CAIRO</option>
                         <option value="76248">EL CERRITO</option>
                         <option value="76250">EL DOVIO</option>
                         <option value="76275">FLORIDA</option>
                         <option value="76306">GINEBRA</option>
                         <option value="76318">GUACARÍ</option>
                         <option value="76364">JAMUNDÍ</option>
                         <option value="76377">LA CUMBRE</option>
                         <option value="76400">LA UNIÓN</option>
                         <option value="76403">LA VICTORIA</option>
                         <option value="76497">OBANDO</option>
                         <option value="76520">PALMIRA</option>
                         <option value="76563">PRADERA</option>
                         <option value="76606">RESTREPO</option>
                         <option value="76616">RIOFRÍO</option>
                         <option value="76622">ROLDANILLO</option>
                         <option value="76670">SAN PEDRO</option>
                         <option value="76736">SEVILLA</option>
                         <option value="76823">TORO</option>
                         <option value="76828">TRUJILLO</option>
                         <option value="76834">TULUÁ</option>
                         <option value="76845">ULLOA</option>
                         <option value="76863">VERSALLES</option>
                         <option value="76869">VIJES</option>
                         <option value="76890">YOTOCO</option>
                         <option value="76892">YUMBO</option>
                         <option value="76895">ZARZAL</option>
                         <option value="81001">ARAUCA</option>
                         <option value="81065">ARAUQUITA</option>
                         <option value="81220">CRAVO NORTE</option>
                         <option value="81300">FORTUL</option>
                         <option value="81591">PUERTO RONDÓN</option>
                         <option value="81736">SARAVENA</option>
                         <option value="81794">TAME</option>
                         <option value="85001">YOPAL</option>
                         <option value="85010">AGUAZUL</option>
                         <option value="85015">CHAMEZA</option>
                         <option value="85125">HATO COROZAL</option>
                         <option value="85136">LA SALINA</option>
                         <option value="85139">MANÍ</option>
                         <option value="85162">MONTERREY</option>
                         <option value="85225">NUNCHÍA</option>
                         <option value="85230">OROCUÉ</option>
                         <option value="85250">PAZ DE ARIPORO</option>
                         <option value="85263">PORE</option>
                         <option value="85279">RECETOR</option>
                         <option value="85300">SABANALARGA</option>
                         <option value="85315">SÁCAMA</option>
                         <option value="85325">SAN LUIS DE PALENQUE</option>
                         <option value="85400">TÁMARA</option>
                         <option value="85410">TAURAMENA</option>
                         <option value="85430">TRINIDAD</option>
                         <option value="85440">VILLANUEVA</option>
                         <option value="86001">MOCOA</option>
                         <option value="86219">COLÓN</option>
                         <option value="86320">ORITO</option>
                         <option value="86568">PUERTO ASÍS</option>
                         <option value="86569">PUERTO CAICEDO</option>
                         <option value="86571">PUERTO GUZMÁN</option>
                         <option value="86573">PUERTO LEGUÍZAMO</option>
                         <option value="86749">SIBUNDOY</option>
                         <option value="86755">SAN FRANCISCO</option>
                         <option value="86757">SAN MIGUEL</option>
                         <option value="86760">SANTIAGO</option>
                         <option value="86865">Valle Del Cauca DEL GUAMUEZ</option>
                         <option value="86885">VILLAGARZÓN</option>
                         <option value="88001">SAN ANDRÉS</option>
                         <option value="88564">PROVIDENCIA</option>
                         <option value="91001">LETICIA</option>
                         <option value="91263">EL ENCANTO</option>
                         <option value="91405">LA CHORRERA</option>
                         <option value="91407">LA PEDRERA</option>
                         <option value="91430">LA VICTORIA</option>
                         <option value="91460">MIRITI - PARANÁ</option>
                         <option value="91530">PUERTO ALEGRÍA</option>
                         <option value="91536">PUERTO ARICA</option>
                         <option value="91540">PUERTO NARIÑO</option>
                         <option value="91669">PUERTO SANTANDER</option>
                         <option value="91798">TARAPACÁ</option>
                         <option value="94001">INÍRIDA</option>
                         <option value="94343">BARRANCO MINAS</option>
                         <option value="94663">MAPIRIPANA</option>
                         <option value="94883">SAN FELIPE</option>
                         <option value="94884">PUERTO COLOMBIA</option>
                         <option value="94885">LA GUADALUPE</option>
                         <option value="94886">CACAHUAL</option>
                         <option value="94887">PANA PANA</option>
                         <option value="94888">MORICHAL</option>
                         <option value="95001">SAN JOSÉ DEL GUAVIARE</option>
                         <option value="95015">CALAMAR</option>
                         <option value="95025">EL RETORNO</option>
                         <option value="95200">MIRAFLORES</option>
                         <option value="97001">MITÚ</option>
                         <option value="97161">CARURU</option>
                         <option value="97511">PACOA</option>
                         <option value="97666">TARAIRA</option>
                         <option value="97777">PAPUNAUA</option>
                         <option value="97889">YAVARATÉ</option>
                         <option value="99001">PUERTO CARREÑO</option>
                         <option value="99524">LA PRIMAVERA</option>
                         <option value="99624">SANTA ROSALÍA</option>
                         <option value="99773">CUMARIBO</option>

                         
                         
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Ciudad Expedicion</label>
                <div class="col-sm-10">
                    <select class="form-control" id="c_exp" name="c_exp">
                        <option value="6">MANIZALES</option>
                         <option value="19">ARMENIA</option>
                         <option value="20">PEREIRA</option>
                         <option value="23">IBAGUE</option>
                         <option value="24">CALI</option>
                         <option value="43">AGUADAS</option>
                         <option value="54">ALCALA</option>
                         <option value="59">ALPUJARRA</option>
                         <option value="63">ALVARADO</option>
                         <option value="68">AMBALEMA</option>
                         <option value="76">ANDALUCIA</option>
                         <option value="80">ANSERMANUEVO</option>
                         <option value="83">ANSERMA</option>
                         <option value="84">ANZOATEGUI</option>
                         <option value="88">APIA</option>
                         <option value="90">ARANZAZU</option>
                         <option value="101">ARGELIA</option>
                         <option value="103">ARMERO</option>
                         <option value="109">ATACO</option>
                         <option value="115">BALBOA</option>
                         <option value="131">BELALCAZAR</option>
                         <option value="132">BELEN DE UMBRIA</option>
                         <option value="148">BOLIVAR</option>
                         <option value="156">BUENAVENTURA</option>
                         <option value="162">BUENAVISTA</option>
                         <option value="163">GUADALAJARA DE BUGA</option>
                         <option value="165">BUGALAGRANDE</option>
                         <option value="170">CAICEDONIA</option>
                         <option value="174">CAJAMARCA</option>
                         <option value="179">CALIMA</option>
                         <option value="183">CALARCA</option>
                         <option value="184">CANDELARIA</option>
                         <option value="203">CARTAGO</option>
                         <option value="206">CARMEN DE APICALA</option>
                         <option value="213">CASABIANCA</option>
                         <option value="228">CHAPARRAL</option>
                         <option value="231">DOSQUEBRADAS</option>
                         <option value="235">CHINCHINA</option>
                         <option value="256">CIRCASIA</option>
                         <option value="260">COELLO</option>
                         <option value="281">CORDOBA</option>
                         <option value="287">COYAIMA</option>
                         <option value="302">CUNDAY</option>
                         <option value="311">DAGUA</option>
                         <option value="316">DOLORES</option>
                         <option value="323">EL AGUILA</option>
                         <option value="333">EL CAIRO</option>
                         <option value="337">EL CERRITO</option>
                         <option value="344">EL DOVIO</option>
                         <option value="367">ESPINAL</option>
                         <option value="370">FALAN</option>
                         <option value="373">FILADELFIA</option>
                         <option value="374">FILANDIA</option>
                         <option value="375">FLANDES</option>
                         <option value="376">FLORIDA</option>
                         <option value="384">FRESNO</option>
                         <option value="410">GENOVA</option>
                         <option value="413">GINEBRA</option>
                         <option value="432">GUATICA</option>
                         <option value="434">GUACARI</option>
                         <option value="436">GUAMO</option>
                         <option value="463">HERVEO</option>
                         <option value="465">HONDA</option>
                         <option value="469">ICONONZO</option>
                         <option value="482">JAMUNDI</option>
                         <option value="498">LA CUMBRE</option>
                         <option value="504">LA DORADA</option>
                         <option value="507">LA CELIA</option>
                         <option value="512">LA MERCED</option>
                         <option value="526">LA VIRGINIA</option>
                         <option value="528">LA UNION</option>
                         <option value="531">LA TEBAIDA</option>
                         <option value="534">LA VICTORIA</option>
                         <option value="542">LERIDA</option>
                         <option value="547">LIBANO</option>
                         <option value="574">MANZANARES</option>
                         <option value="581">MARSELLA</option>
                         <option value="585">MARMATO</option>
                         <option value="587">MARIQUITA</option>
                         <option value="588">MARQUETALIA</option>
                         <option value="590">MARULANDA</option>
                         <option value="591">MELGAR</option>
                         <option value="597">MISTRATO</option>
                         <option value="602">MURILLO</option>
                         <option value="612">MONTENEGRO</option>
                         <option value="628">NATAGAIMA</option>
                         <option value="629">NEIRA</option>
                         <option value="641">NORCASIA</option>
                         <option value="643">OBANDO</option>
                         <option value="652">ORTEGA</option>
                         <option value="659">PACORA</option>
                         <option value="673">PALOCABILDO</option>
                         <option value="674">PALMIRA</option>
                         <option value="678">PALESTINA</option>
                         <option value="697">PENSILVANIA</option>
                         <option value="703">PIEDRAS</option>
                         <option value="706">PIJAO</option>
                         <option value="717">PLANADAS</option>
                         <option value="722">PRADO</option>
                         <option value="723">PRADERA</option>
                         <option value="735">PUEBLO RICO</option>
                         <option value="756">PURIFICACION</option>
                         <option value="764">QUIMBAYA</option>
                         <option value="765">QUINCHIA</option>
                         <option value="777">RESTREPO</option>
                         <option value="782">RIOSUCIO</option>
                         <option value="788">RISARALDA</option>
                         <option value="789">RIOBLANCO</option>
                         <option value="790">RIOFRIO</option>
                         <option value="796">RONCESVALLES</option>
                         <option value="797">ROLDANILLO</option>
                         <option value="798">ROVIRA</option>
                         <option value="816">SALAMINA</option>
                         <option value="833">SAMANA</option>
                         <option value="839">SAN JOSE</option>
                         <option value="852">SAN PEDRO</option>
                         <option value="853">SALDAÑA</option>
                         <option value="863">SAN ANTONIO</option>
                         <option value="869">SAN LUIS</option>
                         <option value="875">SANTA ROSA DE CABAL</option>
                         <option value="888">SANTA ISABEL</option>
                         <option value="890">SANTUARIO</option>
                         <option value="896">SALENTO</option>
                         <option value="926">SEVILLA</option>
                         <option value="967">SUAREZ</option>
                         <option value="974">SUPIA</option>
                         <option value="1034">TORO</option>
                         <option value="1036">TRUJILLO</option>
                         <option value="1039">TULUA</option>
                         <option value="1055">ULLOA</option>
                         <option value="1061">VALLE DE SAN JUAN</option>
                         <option value="1071">VENADILLO</option>
                         <option value="1073">VERSALLES</option>
                         <option value="1075">VICTORIA</option>
                         <option value="1078">VIJES</option>
                         <option value="1079">VILLAHERMOSA</option>
                         <option value="1086">VILLAMARIA</option>
                         <option value="1088">VILLARRICA</option>
                         <option value="1092">VITERBO</option>
                         <option value="1109">YOTOCO</option>
                         <option value="1110">YUMBO</option>
                         <option value="1115">ZARZAL</option>
                         <option value="RIOFRIO">RIOFRIO</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Tipo sangre</label>
                <div class="col-sm-10">
                    <select class="form-control" id="t_san" name="t_san">
                        <option value="A+">A+</option>
                        <option value="A-">A-</option>
                        <option value="B+">B+</option>
                        <option value="B-">B-</option>
                        <option value="AB+">AB+</option>
                        <option value="AB-">AB-</option>
                        <option value="O+">O+</option>
                        <option value="O-">O-</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="email" class="col-sm-2 control-label">Direccion</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="direccion" name="direccion" placeholder="Direccion" required>
                </div>
            </div>
            <div class="form-group">
                <label for="nombre" class="col-sm-2 control-label">Ciudad/Residencia</label>
                    <div class="col-sm-10">
                        <select type="text" class="form-control" id="c_res" name="c_res" placeholder="Ciudad/Residencia" >
                            <option value="6">MANIZALES</option>
                             <option value="19">ARMENIA</option>
                             <option value="20">PEREIRA</option>
                             <option value="23">IBAGUE</option>
                             <option value="24">CALI</option>
                             <option value="43">AGUADAS</option>
                             <option value="54">ALCALA</option>
                             <option value="59">ALPUJARRA</option>
                             <option value="63">ALVARADO</option>
                             <option value="68">AMBALEMA</option>
                             <option value="76">ANDALUCIA</option>
                             <option value="80">ANSERMANUEVO</option>
                             <option value="83">ANSERMA</option>
                             <option value="84">ANZOATEGUI</option>
                             <option value="88">APIA</option>
                             <option value="90">ARANZAZU</option>
                             <option value="101">ARGELIA</option>
                             <option value="103">ARMERO</option>
                             <option value="109">ATACO</option>
                             <option value="115">BALBOA</option>
                             <option value="131">BELALCAZAR</option>
                             <option value="132">BELEN DE UMBRIA</option>
                             <option value="148">BOLIVAR</option>
                             <option value="156">BUENAVENTURA</option>
                             <option value="162">BUENAVISTA</option>
                             <option value="163">GUADALAJARA DE BUGA</option>
                             <option value="165">BUGALAGRANDE</option>
                             <option value="170">CAICEDONIA</option>
                             <option value="174">CAJAMARCA</option>
                             <option value="179">CALIMA</option>
                             <option value="183">CALARCA</option>
                             <option value="184">CANDELARIA</option>
                             <option value="203">CARTAGO</option>
                             <option value="206">CARMEN DE APICALA</option>
                             <option value="213">CASABIANCA</option>
                             <option value="228">CHAPARRAL</option>
                             <option value="231">DOSQUEBRADAS</option>
                             <option value="235">CHINCHINA</option>
                             <option value="256">CIRCASIA</option>
                             <option value="260">COELLO</option>
                             <option value="281">CORDOBA</option>
                             <option value="287">COYAIMA</option>
                             <option value="302">CUNDAY</option>
                             <option value="311">DAGUA</option>
                             <option value="316">DOLORES</option>
                             <option value="323">EL AGUILA</option>
                             <option value="333">EL CAIRO</option>
                             <option value="337">EL CERRITO</option>
                             <option value="344">EL DOVIO</option>
                             <option value="367">ESPINAL</option>
                             <option value="370">FALAN</option>
                             <option value="373">FILADELFIA</option>
                             <option value="374">FILANDIA</option>
                             <option value="375">FLANDES</option>
                             <option value="376">FLORIDA</option>
                             <option value="384">FRESNO</option>
                             <option value="410">GENOVA</option>
                             <option value="413">GINEBRA</option>
                             <option value="432">GUATICA</option>
                             <option value="434">GUACARI</option>
                             <option value="436">GUAMO</option>
                             <option value="463">HERVEO</option>
                             <option value="465">HONDA</option>
                             <option value="469">ICONONZO</option>
                             <option value="482">JAMUNDI</option>
                             <option value="498">LA CUMBRE</option>
                             <option value="504">LA DORADA</option>
                             <option value="507">LA CELIA</option>
                             <option value="512">LA MERCED</option>
                             <option value="526">LA VIRGINIA</option>
                             <option value="528">LA UNION</option>
                             <option value="531">LA TEBAIDA</option>
                             <option value="534">LA VICTORIA</option>
                             <option value="542">LERIDA</option>
                             <option value="547">LIBANO</option>
                             <option value="574">MANZANARES</option>
                             <option value="581">MARSELLA</option>
                             <option value="585">MARMATO</option>
                             <option value="587">MARIQUITA</option>
                             <option value="588">MARQUETALIA</option>
                             <option value="590">MARULANDA</option>
                             <option value="591">MELGAR</option>
                             <option value="597">MISTRATO</option>
                             <option value="602">MURILLO</option>
                             <option value="612">MONTENEGRO</option>
                             <option value="628">NATAGAIMA</option>
                             <option value="629">NEIRA</option>
                             <option value="641">NORCASIA</option>
                             <option value="643">OBANDO</option>
                             <option value="652">ORTEGA</option>
                             <option value="659">PACORA</option>
                             <option value="673">PALOCABILDO</option>
                             <option value="674">PALMIRA</option>
                             <option value="678">PALESTINA</option>
                             <option value="697">PENSILVANIA</option>
                             <option value="703">PIEDRAS</option>
                             <option value="706">PIJAO</option>
                             <option value="717">PLANADAS</option>
                             <option value="722">PRADO</option>
                             <option value="723">PRADERA</option>
                             <option value="735">PUEBLO RICO</option>
                             <option value="756">PURIFICACION</option>
                             <option value="764">QUIMBAYA</option>
                             <option value="765">QUINCHIA</option>
                             <option value="777">RESTREPO</option>
                             <option value="782">RIOSUCIO</option>
                             <option value="788">RISARALDA</option>
                             <option value="789">RIOBLANCO</option>
                             <option value="790">RIOFRIO</option>
                             <option value="796">RONCESVALLES</option>
                             <option value="797">ROLDANILLO</option>
                             <option value="798">ROVIRA</option>
                             <option value="816">SALAMINA</option>
                             <option value="833">SAMANA</option>
                             <option value="839">SAN JOSE</option>
                             <option value="852">SAN PEDRO</option>
                             <option value="853">SALDAÑA</option>
                             <option value="863">SAN ANTONIO</option>
                             <option value="869">SAN LUIS</option>
                             <option value="875">SANTA ROSA DE CABAL</option>
                             <option value="888">SANTA ISABEL</option>
                             <option value="890">SANTUARIO</option>
                             <option value="896">SALENTO</option>
                             <option value="926">SEVILLA</option>
                             <option value="967">SUAREZ</option>
                             <option value="974">SUPIA</option>
                             <option value="1034">TORO</option>
                             <option value="1036">TRUJILLO</option>
                             <option value="1039">TULUA</option>
                             <option value="1055">ULLOA</option>
                             <option value="1061">VALLE DE SAN JUAN</option>
                             <option value="1071">VENADILLO</option>
                             <option value="1073">VERSALLES</option>
                             <option value="1075">VICTORIA</option>
                             <option value="1078">VIJES</option>
                             <option value="1079">VILLAHERMOSA</option>
                             <option value="1086">VILLAMARIA</option>
                             <option value="1088">VILLARRICA</option>
                             <option value="1092">VITERBO</option>
                             <option value="1109">YOTOCO</option>
                             <option value="1110">YUMBO</option>
                             <option value="1115">ZARZAL</option>

                            <option value="RIOFRIO">RIOFRIO</option>
                        </select>
                       
                    </div>
            </div>
                      
            <div class="form-group">
                <label for="nombre" class="col-sm-2 control-label">Telefono</label>
                <div class="col-sm-5">
                    <input type="text" class="form-control" id="tel" name="tel" placeholder="tel" >
                </div>
            </div>
            
            <div class="form-group">
                <label for="SEXO" class="col-sm-2 control-label">Sexo</label>
                <div class="col-sm-10">
                    <select class="form-control" id="sexo" name="sexo">
                        <option value="MASCULINO">MASCULINO</option>
                        <option value="FEMENINO">FEMENINO</option>
                        <option value="OTRO">OTRO</option>
                    </select>
                </div>
            </div>
            

            
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <a href="menu_ingresos.php" class="btn btn-default">Regresar</a>
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
                
            </div>
        </form>
    </div>
</body>
</html>
<head>
        
        


    
   
